version: "2.4"

services:
  web:
    image: railsgreeter
    build: .
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: abunchofjibberishbecausethisisnotontheinternet
      LOG_LEVEL: debug
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    tmpfs:
      - /myapp/tmp/pids
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/health"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:14268:14268"
      - "127.0.0.1:14250:14250"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "127.0.0.1:9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    environment:
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "127.0.0.1:4318:4318"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
